In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [3]:
df = pd.read_csv('fulldata.csv')

In [4]:
df.head()

年份    城市  新建商品住宅价格（元/m^2）   人口（万人）      类型   平均工资（元）      M2(亿元)
0  2019    北京     57549.038970  2153.60    常住人口  173205.0  1918385.98
1  2019    天津     24756.888490  1561.83    常住人口  111602.0  1918385.98
2  2019   石家庄     13648.699460  1103.12    常住人口   78937.0  1918385.98
3  2019    太原     11572.626240   446.19    常住人口   82860.0  1918385.98
4  2019  呼和浩特      9772.957638   313.70  年末常住人口   84105.0  1918385.98

In [5]:
df = df[df['类型']=='常住人口']

In [6]:
df

年份   城市  新建商品住宅价格（元/m^2）   人口（万人）    类型    平均工资（元）      M2(亿元)
0    2019   北京     57549.038970  2153.60  常住人口  173205.00  1918385.98
1    2019   天津     24756.888490  1561.83  常住人口  111602.00  1918385.98
2    2019  石家庄     13648.699460  1103.12  常住人口   78937.00  1918385.98
3    2019   太原     11572.626240   446.19  常住人口   82860.00  1918385.98
9    2019   上海     60358.105400  2428.14  常住人口  151772.00  1918385.98
..    ...  ...              ...      ...   ...        ...         ...
890  2006   湛江      5281.727557   685.64  常住人口   16947.20   322611.51
891  2006   韶关      4179.583924   290.94  常住人口   20033.73   322611.51
892  2006   桂林      4567.821755   488.06  常住人口   17613.40   322611.51
893  2006   北海      2627.180008   157.62  常住人口   15095.79   322611.51
895  2006   遵义      3696.721614   667.85  常住人口   17940.27   322611.51

[490 rows x 7 columns]

In [7]:
predictors = ['人口（万人）','平均工资（元）','M2(亿元)']

In [8]:
target = ['新建商品住宅价格（元/m^2）']

In [9]:
reg = linear_model.LinearRegression()

In [10]:
reg.fit(df[predictors], df[target])

LinearRegression()

In [11]:
reg.intercept_

array([959.15615654])

In [12]:
reg.coef_

array([[ 0.37946128,  0.63512223, -0.02168798]])

In [13]:
fitted = reg.predict(df[predictors])
RMSE = np.sqrt(mean_squared_error(df[target], fitted))
r2 = r2_score(df[target], fitted)
print(f'RMSE: {RMSE:.0f}')
print(f'r2: {r2:.4f}')

RMSE: 5868
r2: 0.7137


In [14]:
model = sm.OLS(df[target], df[predictors].assign(const=1))
results = model.fit()
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:        新建商品住宅价格（元/m^2）   R-squared:                       0.714
Model:                            OLS   Adj. R-squared:                  0.712
Method:                 Least Squares   F-statistic:                     403.8
Date:                Tue, 08 Feb 2022   Prob (F-statistic):          1.56e-131
Time:                        19:50:14   Log-Likelihood:                -4947.1
No. Observations:                 490   AIC:                             9902.
Df Residuals:                     486   BIC:                             9919.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
人口（万人）         0.3795      0.559      0.678      0.4

In [16]:
predictors_= ['平均工资（元）','M2(亿元)']

In [17]:
target_ = ['新建商品住宅价格（元/m^2）']

In [20]:
reg.fit(df[predictors_], df[target_])

LinearRegression()

In [21]:
reg.intercept_

array([1150.50021112])

In [22]:
reg.coef_

array([[ 0.64394668, -0.02203114]])

In [23]:
fitted = reg.predict(df[predictors_])
RMSE = np.sqrt(mean_squared_error(df[target_], fitted))
r2 = r2_score(df[target_], fitted)
print(f'RMSE: {RMSE:.0f}')
print(f'r2: {r2:.4f}')

RMSE: 5871
r2: 0.7134


In [24]:
model = sm.OLS(df[target_], df[predictors_].assign(const=1))
results = model.fit()
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:        新建商品住宅价格（元/m^2）   R-squared:                       0.713
Model:                            OLS   Adj. R-squared:                  0.712
Method:                 Least Squares   F-statistic:                     606.1
Date:                Tue, 08 Feb 2022   Prob (F-statistic):          7.05e-133
Time:                        19:51:58   Log-Likelihood:                -4947.4
No. Observations:                 490   AIC:                             9901.
Df Residuals:                     487   BIC:                             9913.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
平均工资（元）        0.6439      0.019     33.104      0.0